### ISSUE TITLE
Output nothing but the gpu was working

### ISSUE THREAD

**Issue by jaywongs** [npuichigo/openai_trtllm#37]
First of all, thank you for your excellent work. The model I deployed was codellama. I built this project, and two containers started. However, when I used the OpenAI API, it didn't output anything while the GPU was actually working. 

I ran the following Python example:

```shell
python3 openai_completion_stream.py
```

But nothing outputted.

I ran the following curl command:

```shell
curl --location 'http://127.0.0.1:3000/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
    "model": "ensemble",
    "messages": [
        {
            "role": "user",
            "content": "What is machine learning?"
        }
    ],
    "max_tokens": 200,
    "temperature": 0,
    "stop": [""]
}'
```

The response looked like this:

```shell
{
    "id": "cmpl-8959e6ff-41c7-4abf-b9eb-38489480af04",
    "object": "text_completion",
    "created": 1712479707,
    "model": "ensemble",
    "system_fingerprint": null,
    "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": "User: What is machine learning?\nASSISTANT:"
            },
            "finish_reason": "stop"
        }
    ],
    "usage": {
        "prompt_tokens": 0,
        "completion_tokens": 0,
        "total_tokens": 0
    }
}
```
 and the log info looks normal:
```json
{
    "timestamp": "2024-04-07T09:00:51.437413Z",
    "level": "INFO",
    "message": "request: Json(ChatCompletionCreateParams { messages: [User { content: \"What is machine learning?\", name: None }], model: \"ensemble\", frequency_penalty: 0.0, logit_bias: None, max_tokens: 200, n: 1, presence_penalty: 0.0, response_format: None, seed: None, stop: Some([\"\"]), stream: false, temperature: 0.0, top_p: 1.0, user: None })",
    "target": "openai_trtllm::routes::chat",
    "span": {
        "headers": "{\"host\": \"127.0.0.1:3000\", \"user-agent\": \"curl/8.2.1\", \"accept\": \"*/*\", \"content-type\": \"application/json\", \"content-length\": \"220\"}",
        "name": "chat_completions"
    },
    "spans": [
        {
            "http.request.method": "POST",
            "http.route": "/v1/chat/completions",
            "network.protocol.version": "1.1",
            "otel.kind": "Server",
            "otel.name": "POST /v1/chat/completions",
            "server.address": "127.0.0.1:3000",
            "span.type": "web",
            "url.path": "/v1/chat/completions",
            "url.scheme": "",
            "user_agent.original": "curl/8.2.1",
            "name": "HTTP request"
        },
        {
            "headers": "{\"host\": \"127.0.0.1:3000\", \"user-agent\": \"curl/8.2.1\", \"accept\": \"*/*\", \"content-type\": \"application/json\", \"content-length\": \"220\"}",
            "name": "chat_completions"
        }
    ]
}
```
However, when I used curl in the container of triton_trt_llm:

```shell
curl -X POST localhost:8000/v2/models/ensemble/generate_stream -d '{
    "text_input": "What is machine learning?",
    "max_tokens": 200,
    "stream": false,
    "bad_words": "",
    "stop_words": "",
    "pad_id": 2,
    "end_id": 2,
    "return_log_probs": false
}'
```

The answer was just like normal. I'm wondering if any parameters that I input were wrong or if there is any documentation to guide me on what to do next.

Thanks for your kind work again!

**Comment by npuichigo** [comment]
I think you should use the gRPC port of triton. Maybe it's 3001 in your case?

**Comment by jaywongs** [comment]
> I think you should use the gRPC port of triton. Maybe it's 3001 in your case?

I used the default gRPC port (8001) to communicate with Triton.

```
I0407 07:25:59.905119 103 server.cc:677] 
+------------------+---------+--------+
| Model            | Version | Status |
+------------------+---------+--------+
| ensemble         | 1       | READY  |
| postprocessing   | 1       | READY  |
| preprocessing    | 1       | READY  |
| tensorrt_llm     | 1       | READY  |
| tensorrt_llm_bls | 1       | READY  |
+------------------+---------+--------+

I0407 07:25:59.966723 103 metrics.cc:877] Collecting metrics for GPU 0: NVIDIA A100-SXM4-80GB
I0407 07:25:59.969556 103 metrics.cc:770] Collecting CPU metrics
I0407 07:25:59.969690 103 tritonserver.cc:2508] 
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                                           |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                                          |
| server_version                   | 2.43.0                                                                                                                                                                                                          |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data parameters statistics trace logging |
| model_repository_path[0]         | /tensorrtllm_backend/triton_model_repo                                                                                                                                                                          |
| model_control_mode               | MODE_NONE                                                                                                                                                                                                       |
| strict_model_config              | 1                                                                                                                                                                                                               |
| rate_limit                       | OFF                                                                                                                                                                                                             |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                                       |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                                                        |
| min_supported_compute_capability | 6.0                                                                                                                                                                                                             |
| strict_readiness                 | 1                                                                                                                                                                                                               |
| exit_timeout                     | 30                                                                                                                                                                                                              |
| cache_enabled                    | 0                                                                                                                                                                                                               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I0407 07:25:59.971120 103 grpc_server.cc:2519] Started GRPCInferenceService at 0.0.0.0:8001
I0407 07:25:59.971319 103 http_server.cc:4637] Started HTTPService at 0.0.0.0:8000
I0407 07:26:00.012131 103 http_server.cc:320] Started Metrics Service at 0.0.0.0:8002
```
and my docker-compose.yml as following:
```yml
version: "3"

services:
  openai_trtllm:
    image: openai_trtllm
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "3000"
      - "--triton-endpoint"
      - "http://tensorrtllm_backend:8001"
    ports:
      - "3000:3000"
    depends_on:
      - tensorrtllm_backend
    restart: on-failure

  # Triton backend for TensorRT LLM
  tensorrtllm_backend:
    image: triton_trt_llm:latest
    volumes:
      - /tensor/tensorrtllm_backend:/tensorrtllm_backend
    command: 
      - "/bin/bash"
      - "-c"
      - |
        python3 /tensorrtllm_backend/scripts/launch_triton_server.py --world_size=1 --model_repo=/tensorrtllm_backend/triton_model_repo
        tail -f /dev/null
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    shm_size: '2g'
    ulimits:
      memlock: -1
      stack: 67108864
    restart: on-failure
```

i think the port was right here, maybe?
